=== gorun8/easyfk/src/core/base/dtd/component-loader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Project:Easy Web Framework
   Description:
   EasyFK stands for Easy Web Framework.It's an open source product for E-Business / E-Commerce.It
   was launched by a chinese Hezhiping(QQ:110476592) in 2015.The goal of EasyFK is to  provide a
   foundation and starting point for reliable, secure , simple-to-use ,cost-effective ,scalable
   and suitable-for-Chinese E-Business / E-Commerce solutions. With EasyFK, you can get started
   right away without the huge deployment and maintenance costs of E-Business / E-Commerce systems.
   Of course, you can customize it or use it as a framework to implement your most challenging business needs.
   EasyFk is licensed under the Apache License Version 2.0.  You may obtain a copy of the License at
   http://www.apache.org/licenses/LICENSE-2.0
   Author:hezhiping   Email:110476592@qq.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="component-loader">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="load-component"/>
                <xs:element ref="load-components"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="load-component">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.load-component"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.load-component">
        <xs:attribute type="xs:string" name="component-name"/>
        <xs:attribute type="xs:string" name="component-location" use="required"/>
    </xs:attributeGroup>
    <xs:element name="load-components">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.load-components"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.load-components">
        <xs:attribute type="xs:string" name="parent-directory" use="required"/>
    </xs:attributeGroup>
</xs:schema>

=== gorun8/easyfk/src/core/component-load.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Project:Easy Web Framework

Description: This project is based on much more open source projects than ever before,
             and can be applied to mostly web development environment.
Author:hezhiping   Email:110476592@qq.com

=============================================================================================

-->

<component-loader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://www.gorun8.cn/dtds/component-loader.xsd">
    <load-component component-location="base"/>
    <load-component component-location="entity"/>
    <load-component component-location="catalina"/>
    <load-component component-location="webapp"/>
    <load-component component-location="common"/>
    <load-component component-location="security"/>

    <load-component component-location="images"/>
</component-loader>
