=== gorun8/easyfk/src/core/base/dtd/easyfk-application.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Project:Easy Web Framework

Description: This project is based on much more open source projects than ever before,
             and can be applied to mostly web development environment.
Author:hezhiping   Email:110476592@qq.com

=============================================================================================

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="easyfk-application">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="depends-on"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="resource-loader"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="classpath"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="entity-resource"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-resource"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="test-suite"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="keystore"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="webapp"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.easyfk-application"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.easyfk-application">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="enabled" use="optional" default="true"/>
    </xs:attributeGroup>
    <xs:element name="depends-on">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.depends-on">
                <xs:annotation>
                    <xs:documentation>
                        This is yet unimplemented. It's not a trivial implementation because at the moment components are loaded
                        in the order they are found (i.e. alphabetic or creation date).
                        While this feature would require them all to be located first and then reordered and loaded.
                        So, for now, simply follow the README file in hot-deploy root folder.
                    </xs:documentation>
                </xs:annotation>
            </xs:attributeGroup>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.depends-on">
        <xs:attribute type="xs:string" name="component-name" use="required"/>
    </xs:attributeGroup>
    <xs:element name="resource-loader">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.resource-loader"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.resource-loader">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute name="type" default="component">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="component"/>
                    <xs:enumeration value="file"/>
                    <xs:enumeration value="classpath"/>
                    <xs:enumeration value="url"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="prepend-env"/>
        <xs:attribute type="xs:string" name="prefix"/>
    </xs:attributeGroup>
    <xs:element name="classpath">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.classpath"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.classpath">
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="jar"/>
                    <xs:enumeration value="dir"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="location" use="required"/>
    </xs:attributeGroup>
    <xs:element name="entity-resource">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.entity-resource"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.entity-resource">
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="model"/>
                    <xs:enumeration value="group"/>
                    <xs:enumeration value="eca"/>
                    <xs:enumeration value="data"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="reader-name" use="required"/>
        <xs:attribute type="xs:string" name="loader" use="required"/>
        <xs:attribute type="xs:string" name="location" use="required"/>
    </xs:attributeGroup>
    <xs:element name="service-resource">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.service-resource"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.service-resource">
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="model"/>
                    <xs:enumeration value="group"/>
                    <xs:enumeration value="eca"/>
                    <xs:enumeration value="mca"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="loader" use="required"/>
        <xs:attribute type="xs:string" name="location" use="required"/>
    </xs:attributeGroup>
    <xs:element name="test-suite">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.test-suite"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.test-suite">
        <xs:attribute type="xs:string" name="loader" use="required"/>
        <xs:attribute type="xs:string" name="location" use="required"/>
    </xs:attributeGroup>
    <xs:element name="keystore">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.keystore"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.keystore">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="jks"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="password" type="xs:string" use="required"/>
        <xs:attribute name="is-truststore" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="is-certstore" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="loader" use="required"/>
        <xs:attribute type="xs:string" name="location" use="required"/>
    </xs:attributeGroup>
    <xs:element name="webapp">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="virtual-host"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="init-param"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.webapp"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.webapp">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="title"/>
        <xs:attribute type="xs:string" name="description"/>
        <xs:attribute name="menu-name" default="main">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="main"/>
                    <xs:enumeration value="secondary"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="position"/>
        <xs:attribute type="xs:string" name="server" use="required"/>
        <xs:attribute type="xs:string" name="location" use="required"/>
        <xs:attribute type="xs:string" name="mount-point"/>
        <xs:attribute type="xs:string" name="base-permission">
            <xs:annotation><xs:documentation>A user must have ALL of the permissions in the list to access the application</xs:documentation></xs:annotation>
        </xs:attribute>
        <xs:attribute name="privileged" default="false">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="app-bar-display" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="session-cookie-accepted" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:element name="virtual-host">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.virtual-host"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.virtual-host">
        <xs:attribute type="xs:string" name="host-name" use="required"/>
    </xs:attributeGroup>
    <xs:element name="init-param">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.init-param"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.init-param">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
    </xs:attributeGroup>
</xs:schema>

=== gorun8/easyfk/src/baseapps/party/easyfk-application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Project:Easy Web Framework

Description: This project is based on much more open source projects than ever before,
             and can be applied to mostly web development environment.
Author:hezhiping   Email:110476592@qq.com

=============================================================================================

-->
<easyfk-application name="party" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://www.gorun8.cn/dtds/easyfk-application.xsd">
    
    <!-- place the config directory on the classpath to access configuration files -->
    <classpath type="dir" location="config"/>
   
    <!-- load single or multiple external libraries -->
    <classpath type="jar" location="build/lib/*"/>
    <classpath type="jar" location="lib/*"/>
	 <!-- please uncomment below if necessary -->

    <entity-resource type="model" reader-name="main" loader="main" location="entitydef/${db.type}/party.sql"/>
    <entity-resource type="model" reader-name="main" loader="main" location="entitydef/${db.type}/person.sql"/>
    <entity-resource type="seed" reader-name="main" loader="main" location="entitydef/${db.type}/partyseed.sql"/>


    <!-- web baseapps; will be mounted when using the embedded container -->
    <webapp name="party"
        title="会员管理"
        server="default-server"
        location="webapp"
        mount-point="/party"/>
</easyfk-application>
